# Generated by Django 6.0.2 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specifications', models.TextField()),
                ('image', models.ImageField(upload_to='laptops/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
